version: "3"

services:
  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api

  api:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
